### Criar um nova fazenda
POST http://localhost:3000/fazendas
Content-Type: application/json
Authorization: Bearer <Token>

{
    "nome": "Fazenda Bonifacio",
    "cidade": "Conceição de Ipanema",
    "estado": "MG",
    "areaTotal": "1000",
    "areaAgricultavel": "800",
    "areaVegetacao": "200",
    "produtorId": 4
}

###

### Listar todas as fazendas
GET http://localhost:3000/fazendas
Content-Type: application/json
Authorization: Bearer <Token>

###

### Obter uma fazenda específica
GET http://localhost:3000/fazendas/1
Content-Type: application/json
Authorization: Bearer <Token>

###

### Atualizar uma fazenda
PUT http://localhost:3000/fazendas/1
Content-Type: application/json
Authorization: Bearer <Token>

{
    "nome": "Fazenda Boa Vista Atualizada",
    "cidade": "Campo Grande",
    "estado": "MS",
    "areaTotal": "1200",
    "areaAgricultavel": "900",
    "areaVegetacao": "300",
    "produtorId": 2
}
###

### Deletar uma fazenda
DELETE http://localhost:3000/fazendas/1
Content-Type: application/json
Authorization: Bearer <Token>

###