### Criar um nova fazenda
POST http://localhost:3000/fazendas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsaWNlQGV4YW1wbGUuY29tIiwic3ViIjoxLCJub21lIjoiQWxpY2UiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NTcyNDE4MSwiZXhwIjoxNzU1NzI3NzgxfQ.EihW2gMVlJ115dicoGyErYif2sCDLSY2eu3Q-S7qOHI

{
    "nome": "Fazenda Bonifacio",
    "cidade": "Conceição de Ipanema",
    "estado": "MG",
    "areaTotal": "1000",
    "areaAgricultavel": "800",
    "areaVegetacao": "200",
    "produtorId": 4
}

###

### Listar todas as fazendas
GET http://localhost:3000/fazendas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkFsaWNlQGV4YW1wbGUuY29tIiwic3ViIjoxLCJub21lIjoiQWxpY2UiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NTY1MTQ5OSwiZXhwIjoxNzU1NjU1MDk5fQ.qu8vHsL459tHkb3kd5CFPvRGazp9EHv8V5f44ODnnlE

###

### Obter uma fazenda específica
GET http://localhost:3000/fazendas/1
Content-Type: application/json
###

### Atualizar uma fazenda
PUT http://localhost:3000/fazendas/1
Content-Type: application/json

{
    "nome": "Fazenda Boa Vista Atualizada",
    "cidade": "Campo Grande",
    "estado": "MS",
    "areaTotal": "1200",
    "areaAgricultavel": "900",
    "areaVegetacao": "300",
    "produtorId": 2
}
###

### Deletar uma fazenda
DELETE http://localhost:3000/fazendas/1
Content-Type: application/json
###