### Criar um novo produtor
POST http://localhost:3000/produtor
Content-Type: application/json
Authorization: Bearer <Token>
{
    "nome": "Teste",
    "cpfOuCnpj": "65554647049"
}
###

### Listar todos os produtores
GET http://localhost:3000/produtor
Content-Type: application/json
Authorization: Bearer <Token>
###

### Obter um produtor específico
GET http://localhost:3000/produtor/6
Content-Type: application/json
Authorization: Bearer <Token>
###

### Atualizar um produtor
PUT http://localhost:3000/produtor/6
Content-Type: application/json
Authorization: Bearer <Token>

{
    "nome": "Usuario Teste",
    "cpfOuCnpj": "12435243677"
}
###

### Deletar um produtor
DELETE http://localhost:3000/produtor/2
Content-Type: application/json
Authorization: Bearer <Token>

